### ISSUE TITLE
tflint --init is not run prior to tflint execution

### ISSUE THREAD

**Issue by portusato** [nvuillam/mega-linter#648] opened 2021-08-13 16:09 UTC
**Describe the bug**
I'm getting an error when running the tflint linter:
\### Processed [TERRAFORM] files
\- Using [tflint v0.29.1] https://github.com/terraform-linters/tflint
\- Mega-Linter key: [TERRAFORM_TFLINT]
\- Rules config: [/github/workspace/.tflint.hcl]
[tflint] main.tf - ERROR - 1 error(s)
--Error detail:
Failed to initialize plugins. An error occurred:

Error: Plugin \`azurerm\` not found. Did you run \`tflint --init\`?

**To Reproduce**
1. Commit a .tflint.hcl like this:

plugin "azurerm" {
    enabled = true
    version = "0.12.0"
    source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
}

2. Commit a .tf file that uses the azurerm provider
3. Run mega-linter

**Expected behavior**
Output of tflint with the linting results for my .tf file.

**Additional information**
I think the hypothesis for the error generated by tflint (that tflint --init has not been run) is correct because when I run manually tflint without previously running tflint --init I get the same error.

Furthermore, if I set in .tflint.hcl the version of the azurerm plugin to 0.13.0, a version that currently does not exist, when I run tflint --init manually I receive an error as expected "Error: Failed to fetch GitHub releases: GET https://api.github.com/repos/terraform-linters/tflint-ruleset-azurerm/releases/tags/v0.13.0: 404 Not Found []". On the contrary, the run inside mega-linter keeps failing with the same original error message (Error: Plugin \`azurerm\` not found. Did you run \`tflint --init\`?). I think that clearly indicates that my .tflint.hcl is not being used.

**Comment by nvuillam** [comment] 2021-08-13 16:40
It seems you're right , init is not called

https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/terraform.megalinter-descriptor.yml

Before i make a patch, as workaround you can call tflint --init in a pre-command :)

https://nvuillam.github.io/mega-linter/configuration/#pre-commands

**Comment by portusato** [comment] 2021-08-13 18:20
Many thanks @nvuillam . I'm new to Mega Linter and at a moment it occurred to me that something like a pre-command may exist, but I had not gotten there yet. I tried your suggestion with:
```
PRE_COMMANDS:
  - command: tflint --init
    cwd: "workspace"
```
It installs the plugin, but the tflint checker fails with:
`Error: Incompatible API version with plugin "azurerm". Plugin version: 9, TFLint versions: [8]`

I think I may be able to specify the plugin version that I want in the tflint configuration file, but I think this is a side effect of using tflint v0.29.1. Starting from v0.30.0 tflint docker images have been migrated from wata727/tflint to ghcr.io/terraform-linters/tflint. See [release notes](https://github.com/terraform-linters/tflint/releases/tag/v0.30.0). Should I create a separate ticket to update the registry? (actually I think I can produce a PR for that if that's fine with you).

**Comment by nvuillam** [comment] 2021-08-13 18:26
Please be my guest to create the PR :)

https://nvuillam.github.io/mega-linter/contributing/

**Comment by nvuillam** [comment] 2021-08-13 22:24
@portusato I made the PR, i'll merge it once CI passes :)

**Comment by portusato** [comment] 2021-08-13 22:52
Thanks!

**Comment by nvuillam** [comment] 2021-08-14 11:06
@portusato please can you check with latest / insiders version and confirm that it's ok with your plugin ? thanks !

**Comment by portusato** [comment] 2021-08-14 16:05
Many thanks @nvuillam . I've tested with the insiders version of the GitHub action. I confirm that the latest version of tflint from the new registry is used and the workflow works as expected! That's great. You're the boss!!!

I noticed in #649 that you added `RUN tflint --init` to the dockerfile. That is in order to activate the default tflint config file, right? It does not allow the user to use their own .tflint.hcl, as this is something that needs to be done after the checkout. So we still need to use the pre-command. I was looking at your code to see where I could add a step before a specific linter runs, but could not find it. Anyway, your suggestion of using pre-commands works good and my workflow is rolling! I love it!

**Comment by nvuillam** [comment] 2021-08-15 19:29
@portusato I added it because I thought you requested it, do you mean that it should be removed ? :)

**Comment by portusato** [comment] 2021-08-15 20:59
@nvuillam, tflint --init needs to be executed in the presence of the user's .tflint.hcl file. What that does is download the specific plugins that the user needs, e.g azurerm.
If I understand correctly, the tflint --init you added is executed while building the mega-linter docker image, so no info about each user's plugins is available.

**Comment by calexandre** [comment] 2021-08-16 11:11
I've also stumbled on this issue  due to `tflint` error...

I have tflint binary installed and it runs without any issues locally, but with mega-linter insiders I have this error:

```
Results of tflint linter (version 0.31.0)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/terraform_tflint/
-----------------------------------------------

❌ [ERROR] main.tf
    Failed to initialize plugins. An error occurred:
    
    Error: Plugin `google` not found. Did you run `tflint --init`?

❌ [ERROR] variables.tf
    Failed to initialize plugins. An error occurred:
    
    Error: Plugin `google` not found. Did you run `tflint --init`?
```

**Comment by calexandre** [comment] 2021-08-16 11:26
So I added a pre-command to issue the `tflint --init` command, and now I have a different error:

```
Results of tflint linter (version 0.31.0)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/terraform_tflint/
-----------------------------------------------

❌ [ERROR] main.tf
    Failed to check ruleset. An error occurred:
    
    Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

❌ [ERROR] variables.tf
    Failed to check ruleset. An error occurred:
    
    Error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

Note that `tflint` is running locally without any issues.

**Comment by nvuillam** [comment] 2021-08-20 12:46
I understand that calling tflint --init during Docker build is useless

What if i define `pre_command` at descriptor linter level, with default value for tflint to `tflint --init` ?
Would it be ok so it would work by default, without forcing users to define their own PRE_COMMAND in .mega-linter.yml file ?

**Comment by calexandre** [comment] 2021-08-20 16:31
> I understand that calling tflint --init during Docker build is useless
> 
> What if i define `pre_command` at descriptor linter level, with default value for tflint to `tflint --init` ?
> Would it be ok so it would work by default, without forcing users to define their own PRE_COMMAND in .mega-linter.yml file ?

I believe it would be okay. This command needs to be run before the linter is actually used.

**Comment by nvuillam** [comment] 2021-08-21 10:03
Working on it :)

**Comment by nvuillam** [comment] 2021-08-21 12:07
@portusato @calexandre > I merged a PR allowing to define PRE_COMMANDS and POST_COMMANDS at linter level or directly in descriptor

I added `tflint --init` by default in tflint descriptor, so it will be called just before the linter , only when the linter is activated

Please can you confirm with latest/insiders version that this is the behaviour you need ?

**Comment by nvuillam** [comment] 2021-08-21 12:09
Note: the latest/insiders image will be available in a few dozen minutes, after this action -> https://github.com/nvuillam/mega-linter/runs/3389087263?check_suite_focus=true

**Comment by calexandre** [comment] 2021-08-21 12:52
Thank you @nvuillam I will test it once I have the chance :)

**Comment by dgteixeira** [comment] 2021-08-23 13:28
Hey @nvuillam, the addition of `tflint --init ` by default is not within the v4.44.1 , is it?
If I use latest I don't need the pre-command, however in that version I do need it.
Error and version provided:
` - Image Creation Date: 2021-08-20T06:33:28Z
 - Image Revision: 28619301
 - Image Version: v4.44.1`
 
 `Failed to initialize plugins. An error occurred:

Error: Plugin `google` not found. Did you run `tflint --init`?`

**Comment by nvuillam** [comment] 2021-08-23 19:31
> Hey @nvuillam, the addition of tflint --init by default is not within the v4.44.1 , is it?

Not in a released version yet, but as you just confirmed in works it will be soon :)

**Closed** 2021-08-23 19:31 UTC
Labels: bug

**Comment by rajuvadarevu** [comment] 2021-08-31 12:01
yes, tflint --init error is still there in v4.44.1 version

**Comment by nvuillam** [comment] 2021-08-31 12:47
@rajuvadarevu I should release v4.45.0 in a few hours :)

**Comment by rajuvadarevu** [comment] 2021-08-31 13:35
Now I get a similar kind of error for **terraform init** with tflint

### Processed [TERRAFORM] files
- Using [tflint v0.31.0] https://github.com/terraform-linters/tflint
- Mega-Linter key: [TERRAFORM_TFLINT]
- Rules config: [/github/workspace/.tflint.hcl]
[tflint] examples/jenkins-sandbox/main.tf - ERROR - 1 error(s)
--Error detail:
Failed to load configurations. 1 error(s) occurred:

Error: `azure-vm` module is not found. Did you run `terraform init`?

  on /github/workspace/examples/jenkins-sandbox/main.tf line 7, in module "azure-vm":
   7: module "azure-vm" {

When checked with tflint 0.31.0 standalone, it does not give this **terraform init** error

Tried adding **terraform init** as one of the PRE_COMMANDS, but no luck, still getting the error
PRE_COMMANDS:
  - command: terraform version
    cwd: "workspace"
  - command: terraform init
    cwd: "workspace"
  - command: tflint --init
    cwd: "workspace"

Any solution ?

**Comment by dgteixeira** [comment] 2021-09-06 16:46
@nvuillam confirmed it works on v4.45.0 without the pre-command for TFLINT.
Thanks!

**Comment by nvuillam** [comment] 2021-09-06 17:58
@dgteixeira thanks for the feedback :)
